//! C ABI for librouting. Exposes Layer-3 router lifecycle + Layer-1 codec
//! helpers via `extern "C"`. The header is generated by `cbindgen` in
//! `build.rs` and lands at `include/lr_ffi.h`.
//!
//! # Safety
//!
//! Every entry point wraps its body in `catch_unwind` to convert panics into
//! `LR_ERR_PANIC`. Returned Rust memory is owned by the caller and must be
//! freed via the matching `lr_*_free` / `lr_*_destroy` functions.
//!
//! All `extern "C"` entry points are inherently unsafe; we guard against the
//! most common misuse by null-checking pointers.

#![allow(unsafe_code)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]
#![allow(clippy::drop_non_drop)]

pub mod bytes;
pub mod codec;
pub mod error;
pub mod handle;
pub mod router;

pub use error::{lr_error_t, lr_last_error, LrError};
pub use handle::{lr_bytes_t, lr_router_t};
