use std::env;
use std::path::PathBuf;

fn main() {
    // Only generate the header when cbindgen is available; some build
    // environments (e.g. docs.rs) disable it.
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package = std::path::Path::new(&crate_dir)
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("include"))
        .unwrap_or_else(|| PathBuf::from(&crate_dir).join("include"));
    let _ = std::fs::create_dir_all(&package);
    let header_path = package.join("lr_ffi.h");

    let cfg = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("LR_FFI_H".to_string()),
        autogen_warning: Some(
            "/* AUTO-GENERATED by cbindgen — do not edit. Re-generate via `cargo build -p lr-ffi`. */".to_string()
        ),
        ..Default::default()
    };

    match cbindgen::generate_with_config(&crate_dir, cfg) {
        Ok(out) => {
            if std::env::var("DOCS_RS").is_ok() {
                return; // don't fail docs.rs builds on header generation
            }
            out.write_to_file(&header_path);
        }
        Err(e) => {
            eprintln!("cargo:warning=cbindgen failed: {}", e);
        }
    }

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/handle.rs");
    println!("cargo:rerun-if-changed=src/error.rs");
    println!("cargo:rerun-if-changed=src/bytes.rs");
    println!("cargo:rerun-if-changed=src/router.rs");
    println!("cargo:rerun-if-changed=src/codec.rs");
}
