use std::env;
use std::path::PathBuf;

fn main() {
    // Only generate the header when cbindgen is available; some build
    // environments (e.g. docs.rs) disable it.
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package = std::path::Path::new(&crate_dir)
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("include"))
        .unwrap_or_else(|| PathBuf::from(&crate_dir).join("include"));
    let _ = std::fs::create_dir_all(&package);
    let header_path = package.join("lr_ffi.h");

    let cfg = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("LR_FFI_H".to_string()),
        autogen_warning: Some(
            "/* AUTO-GENERATED by cbindgen — do not edit. Re-generate via `cargo build -p lr-ffi`. */".to_string()
        ),
        export: cbindgen::ExportConfig {
            // cbindgen 0.29 picks LrError up from the lib.rs
            // re-export and emits a C23 fixed-width enum whose
            // pre-C23 fallback (`typedef int32_t LrError`) conflicts
            // with the enum definition — breaking every C consumer.
            // No exported entry point uses the enum (they return
            // plain int32_t), so exclude it from the header.
            exclude: vec!["LrError".to_string(), "lr_error_t".to_string()],
            ..Default::default()
        },
        after_includes: Some(
            r#"
/* Wire protocol ids for lr_router_add_redistribution_pipe (LrProtocol). */
#define LR_PROTO_BGP 0
#define LR_PROTO_OSPF 1
#define LR_PROTO_OSPF3 2
#define LR_PROTO_BABEL 3
#define LR_PROTO_STATIC 4
#define LR_PROTO_CONNECTED 5

/* Metric policy ids for lr_router_add_redistribution_pipe (LrMetricPolicy). */
#define LR_METRIC_INHERIT 0
#define LR_METRIC_FIXED 1
#define LR_METRIC_ADD 2

/* Event kind ids for lr_router_poll_events (lr_event_kind_t) - the
 * enum itself is exported, the defines exist for pre-C23 consumers
 * that cannot name enum values in preprocessor tests. */
#define LR_EVENT_PEER_STATE 1
#define LR_EVENT_ROUTE_INSTALLED 2
#define LR_EVENT_ROUTE_WITHDRAWN 3
#define LR_EVENT_LOG 4
#define LR_EVENT_PREFIX_ADVERTISED 5
#define LR_EVENT_PREFIX_RETRACTED 6
#define LR_EVENT_PROTOCOL_ERROR 7
#define LR_EVENT_MAX_PREFIX_EXCEEDED 8
#define LR_EVENT_MAX_PREFIX_THRESHOLD 9

/* MaxPrefixExceeded action ids (lr_event_t::action). */
#define LR_MAX_PREFIX_WARN 0
#define LR_MAX_PREFIX_TEARDOWN 1
#define LR_MAX_PREFIX_RESTART 2
"#.to_string(),
        ),
        ..Default::default()
    };

    match cbindgen::generate_with_config(&crate_dir, cfg) {
        Ok(out) => {
            if std::env::var("DOCS_RS").is_ok() {
                return; // don't fail docs.rs builds on header generation
            }
            out.write_to_file(&header_path);
        }
        Err(e) => {
            eprintln!("cargo:warning=cbindgen failed: {}", e);
        }
    }

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/handle.rs");
    println!("cargo:rerun-if-changed=src/error.rs");
    println!("cargo:rerun-if-changed=src/bytes.rs");
    println!("cargo:rerun-if-changed=src/router.rs");
    println!("cargo:rerun-if-changed=src/policy.rs");
    println!("cargo:rerun-if-changed=src/codec.rs");
    println!("cargo:rerun-if-changed=src/events.rs");
}
