"""librouting Python bindings (CFFI-based).

Exposes Layer-3 router lifecycle + Layer-1 codec helpers.
The shared library `liblr_ffi.so` is loaded at import time. The path can be
overridden via the `LIBROUTING_LIB` environment variable; otherwise we look
in the workspace's `target/release` directory.
"""

from .router import (
    METRIC_ADD,
    METRIC_FIXED,
    METRIC_INHERIT,
    PROTO_BABEL,
    PROTO_BGP,
    PROTO_CONNECTED,
    PROTO_OSPF,
    PROTO_OSPF3,
    PROTO_STATIC,
    Damping,
    LrError,
    Router,
    abi_version,
    last_error,
    mpls_platform_labels,
)
from .roa import ROA_INVALID, ROA_NOT_FOUND, ROA_VALID, RoaStore
from .policy import (
    EVAL_DENY,
    EVAL_FALLTHROUGH,
    EVAL_PERMIT,
    MATCH_AS_PATH_IN,
    MATCH_COMMUNITY_IN,
    MATCH_NEXT_HOP_IN,
    MATCH_PREFIX_IN,
    MATCH_PROTOCOL_IS,
    SET_ADD_COMMUNITY,
    SET_LOCAL_PREF,
    SET_MED,
    SET_METRIC,
    SET_NEXT_HOP,
    SET_PREPEND_AS,
    SET_TAG,
    VERDICT_CONTINUE,
    VERDICT_DENY,
    VERDICT_PERMIT,
    AsPathFilter,
    CommunityEntry,
    Match,
    PrefixList,
    Resolver,
    Route,
    RouteMap,
    Set,
)
from .codec import (
    encode_keepalive,
    encode_open,
    encode_notification,
    encode_update_withdraw_v4,
    encode_update_announce_v4,
    decode_bgp,
    decode_ospf_v2,
    decode_babel,
    encode_srv6_srh,
    decode_srv6_srh,
)

__all__ = [
    "Router",
    "Damping",
    "PROTO_BGP",
    "PROTO_OSPF",
    "PROTO_OSPF3",
    "PROTO_BABEL",
    "PROTO_STATIC",
    "PROTO_CONNECTED",
    "METRIC_INHERIT",
    "METRIC_FIXED",
    "METRIC_ADD",
    "RoaStore",
    "ROA_VALID",
    "ROA_NOT_FOUND",
    "ROA_INVALID",
    "encode_keepalive",
    "encode_open",
    "encode_notification",
    "encode_update_withdraw_v4",
    "encode_update_announce_v4",
    "decode_bgp",
    "decode_ospf_v2",
    "decode_babel",
    "encode_srv6_srh",
    "decode_srv6_srh",
    "abi_version",
    "last_error",
    "mpls_platform_labels",
    "LrError",
    # D5.3 policy objects
    "Route",
    "PrefixList",
    "RouteMap",
    "Resolver",
    "AsPathFilter",
    "CommunityEntry",
    "Match",
    "Set",
    "MATCH_PREFIX_IN",
    "MATCH_AS_PATH_IN",
    "MATCH_COMMUNITY_IN",
    "MATCH_PROTOCOL_IS",
    "MATCH_NEXT_HOP_IN",
    "SET_LOCAL_PREF",
    "SET_MED",
    "SET_NEXT_HOP",
    "SET_PREPEND_AS",
    "SET_ADD_COMMUNITY",
    "SET_METRIC",
    "SET_TAG",
    "VERDICT_CONTINUE",
    "VERDICT_PERMIT",
    "VERDICT_DENY",
    "EVAL_FALLTHROUGH",
    "EVAL_DENY",
    "EVAL_PERMIT",
]

__version__ = "1.0.0-rc.3"
