#ifndef LR_FFI_H
#define LR_FFI_H

/* AUTO-GENERATED by cbindgen — do not edit. Re-generate via `cargo build -p lr-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Rust-allocated byte slice that the embedder owns and must free.
 */
typedef struct lr_bytes_t {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} lr_bytes_t;

/**
 * Opaque router handle. C side never touches internals.
 */
typedef struct OpaqueRouter {
  uint8_t _private[0];
} OpaqueRouter;

typedef struct OpaqueRouter *lr_router_t;

/**
 * Free an `lr_bytes_t` previously returned from any `lr_*` function. Safe to
 * call with a NULL pointer.
 *
 * # Safety
 * The pointer must have been produced by an `lr_*` function.
 */
void lr_bytes_free(struct lr_bytes_t *b);

/**
 * Length of an `lr_bytes_t`.
 */
uintptr_t lr_bytes_len(const struct lr_bytes_t *b);

/**
 * Pointer to the data of an `lr_bytes_t`. NULL if `b` is NULL.
 */
const uint8_t *lr_bytes_ptr(const struct lr_bytes_t *b);

/**
 * Decode one BGP message from `data`. Returns 0 on success (and writes a
 * `lr_bytes_t` containing the message type byte at offset 0 + body to
 * `out`). Negative on error.
 */
int32_t lr_bgp_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Encode a BGP message given the body bytes. The first byte of `data` is the
 * message type (1=OPEN, 2=UPDATE, 3=NOTIF, 4=KEEPALIVE, 5=ROUTE-REFRESH).
 * Currently only KEEPALIVE is supported for round-trip FFI testing.
 */
int32_t lr_bgp_encode_keepalive(struct lr_bytes_t *out);

int32_t lr_ospf_decode_v2(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

int32_t lr_babel_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Get the last error message. Returned string is NUL-terminated UTF-8.
 *
 * # Safety
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *lr_last_error(void);

/**
 * ABI version packed as u32. Compare to `lr_core::ABI_VERSION`.
 */
uint32_t lr_abi_version(void);

/**
 * Create a new router instance.
 */
lr_router_t lr_router_new(void);

/**
 * Destroy a router instance. Safe to call with NULL.
 *
 * # Safety
 * `r` must have been returned by `lr_router_new` and not yet destroyed.
 */
void lr_router_destroy(lr_router_t r);

/**
 * Add a BGP session. Returns 0 on success, negative on error. The session
 * handle is written to `out_handle`.
 */
int32_t lr_router_add_bgp_session(lr_router_t r,
                                  uint32_t local_as,
                                  uint32_t peer_as,
                                  uint32_t local_bgp_id,
                                  uint16_t hold_time,
                                  uint16_t keepalive,
                                  uint8_t asn4,
                                  uint64_t *out_handle);

/**
 * Push bytes from the peer transport into a session.
 *
 * # Safety
 * `bytes` must be a valid pointer to `len` bytes.
 */
int32_t lr_router_feed_input(lr_router_t r, uint64_t session, const uint8_t *bytes, uintptr_t len);

/**
 * Drain bytes from a session to send to the peer transport.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_drain_output(lr_router_t r, uint64_t session, struct lr_bytes_t *out);

/**
 * Advance the router clock.
 */
int32_t lr_router_tick(lr_router_t r, uint64_t now_ms);

/**
 * Start a BGP session (no-op placeholder; FSM is driven by tick/feed).
 */
int32_t lr_router_start_session(lr_router_t r, uint64_t session);

#endif  /* LR_FFI_H */
