#ifndef LR_FFI_H
#define LR_FFI_H

/* AUTO-GENERATED by cbindgen — do not edit. Re-generate via `cargo build -p lr-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Rust-allocated byte slice that the embedder owns and must free.
 */
typedef struct lr_bytes_t {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} lr_bytes_t;

/**
 * Opaque router handle. C side never touches internals.
 */
typedef struct OpaqueRouter {
  uint8_t _private[0];
} OpaqueRouter;

typedef struct OpaqueRouter *lr_router_t;

/**
 * Free an `lr_bytes_t` previously returned from any `lr_*` function. Safe to
 * call with a NULL pointer.
 *
 * # Safety
 * The pointer must have been produced by an `lr_*` function.
 */
void lr_bytes_free(struct lr_bytes_t *b);

/**
 * Length of an `lr_bytes_t`.
 */
uintptr_t lr_bytes_len(const struct lr_bytes_t *b);

/**
 * Pointer to the data of an `lr_bytes_t`. NULL if `b` is NULL.
 */
const uint8_t *lr_bytes_ptr(const struct lr_bytes_t *b);

/**
 * Decode one BGP message from `data`. Returns 0 on success (and writes a
 * `lr_bytes_t` containing the message type byte at offset 0 + body to
 * `out`). Negative on error.
 */
int32_t lr_bgp_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Encode a BGP message given the body bytes. The first byte of `data` is the
 * message type (1=OPEN, 2=UPDATE, 3=NOTIF, 4=KEEPALIVE, 5=ROUTE-REFRESH).
 * Currently only KEEPALIVE is supported for round-trip FFI testing.
 */
int32_t lr_bgp_encode_keepalive(struct lr_bytes_t *out);

int32_t lr_ospf_decode_v2(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

int32_t lr_babel_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Get the last error message. Returned string is NUL-terminated UTF-8.
 *
 * # Safety
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *lr_last_error(void);

/**
 * ABI version packed as u32. Compare to `lr_core::ABI_VERSION`.
 */
uint32_t lr_abi_version(void);

/**
 * Create a new router instance.
 */
lr_router_t lr_router_new(void);

/**
 * Destroy a router instance. Safe to call with NULL.
 *
 * # Safety
 * `r` must have been returned by `lr_router_new` and not yet destroyed.
 */
void lr_router_destroy(lr_router_t r);

/**
 * Add a BGP session. Returns 0 on success, negative on error. The session
 * handle is written to `out_handle`.
 *
 * Graceful restart (RFC 4724) is enabled with a 120 s restart time;
 * Long-Lived Graceful Restart (RFC 9494) is disabled. Use
 * [`lr_router_add_bgp_session_ext`] to configure both.
 */
int32_t lr_router_add_bgp_session(lr_router_t r,
                                  uint32_t local_as,
                                  uint32_t peer_as,
                                  uint32_t local_bgp_id,
                                  uint16_t hold_time,
                                  uint16_t keepalive,
                                  uint8_t asn4,
                                  uint64_t *out_handle);

/**
 * Extended session creation with graceful-restart knobs.
 *
 * - `graceful_restart` / `gr_restart_time`: RFC 4724 advertisement and
 *   stale-route retention (seconds; restart time is clamped to 12 bits).
 * - `long_lived_gr` / `llgr_stale_time`: RFC 9494 Long-Lived Graceful
 *   Restart — LLGR requires GR per RFC 9494 §4.1, so when
 *   `long_lived_gr` is set with `graceful_restart` clear the LLGR
 *   capability is not advertised.
 * - `llgr_max_stale_time`: optional local cap (seconds) on the stale time
 *   received from the peer; 0 disables the cap (RFC 9494 §4.2).
 */
int32_t lr_router_add_bgp_session_ext(lr_router_t r,
                                      uint32_t local_as,
                                      uint32_t peer_as,
                                      uint32_t local_bgp_id,
                                      uint16_t hold_time,
                                      uint16_t keepalive,
                                      uint8_t asn4,
                                      uint8_t graceful_restart,
                                      uint16_t gr_restart_time,
                                      uint8_t long_lived_gr,
                                      uint32_t llgr_stale_time,
                                      uint32_t llgr_max_stale_time,
                                      uint64_t *out_handle);

/**
 * Push bytes from the peer transport into a session.
 *
 * # Safety
 * `bytes` must be a valid pointer to `len` bytes.
 */
int32_t lr_router_feed_input(lr_router_t r, uint64_t session, const uint8_t *bytes, uintptr_t len);

/**
 * Drain bytes from a session to send to the peer transport.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_drain_output(lr_router_t r, uint64_t session, struct lr_bytes_t *out);

/**
 * Advance the router clock.
 */
int32_t lr_router_tick(lr_router_t r, uint64_t now_ms);

/**
 * Start a session: drives the protocol FSM into operation (BGP:
 * ManualStart + TransportOpen). Call once the transport is connected.
 */
int32_t lr_router_start_session(lr_router_t r, uint64_t session);

/**
 * Set the per-prefix RFC 4271 MRAI interval for a BGP session.
 *
 * A zero interval disables batching and flushes any pending UPDATEs.
 */
int32_t lr_router_set_mrai(lr_router_t r, uint64_t session, uint64_t interval_ms);

/**
 * Request an RFC 2918 route refresh from an established BGP peer.
 *
 * Returns 1 when a request was queued, 0 when the session has not negotiated
 * route refresh, and a negative value for invalid handles or inputs.
 */
int32_t lr_router_request_route_refresh(lr_router_t r,
                                        uint64_t session,
                                        uint16_t afi,
                                        uint8_t safi);

/**
 * Originate a local IPv4 route: `prefix_addr` is 4 bytes, `prefix_len` is
 * the prefix length, `next_hop` is 4 bytes or NULL. The route is injected
 * into Loc-RIB and advertised to all established BGP peers.
 *
 * # Safety
 * `prefix_addr` and `next_hop` (when non-NULL) must be valid pointers to
 * 4 readable bytes.
 */
int32_t lr_router_originate_v4(lr_router_t r,
                               const uint8_t *prefix_addr,
                               uint8_t prefix_len,
                               const uint8_t *next_hop);

/**
 * Number of routes currently in Loc-RIB.
 */
int64_t lr_router_rib_len(lr_router_t r);

/**
 * Dump the Loc-RIB as a text table (one route per line). The caller owns
 * the returned bytes and must free them with `lr_bytes_free`.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_rib_dump(lr_router_t r, struct lr_bytes_t *out);

#endif  /* LR_FFI_H */
