#ifndef LR_FFI_H
#define LR_FFI_H

/* AUTO-GENERATED by cbindgen — do not edit. Re-generate via `cargo build -p lr-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Wire protocol ids for lr_router_add_redistribution_pipe (LrProtocol). */
#define LR_PROTO_BGP 0
#define LR_PROTO_OSPF 1
#define LR_PROTO_OSPF3 2
#define LR_PROTO_BABEL 3
#define LR_PROTO_STATIC 4
#define LR_PROTO_CONNECTED 5

/* Metric policy ids for lr_router_add_redistribution_pipe (LrMetricPolicy). */
#define LR_METRIC_INHERIT 0
#define LR_METRIC_FIXED 1
#define LR_METRIC_ADD 2

/* Event kind ids for lr_router_poll_events (lr_event_kind_t) - the
 * enum itself is exported, the defines exist for pre-C23 consumers
 * that cannot name enum values in preprocessor tests. */
#define LR_EVENT_PEER_STATE 1
#define LR_EVENT_ROUTE_INSTALLED 2
#define LR_EVENT_ROUTE_WITHDRAWN 3
#define LR_EVENT_LOG 4
#define LR_EVENT_PREFIX_ADVERTISED 5
#define LR_EVENT_PREFIX_RETRACTED 6
#define LR_EVENT_PROTOCOL_ERROR 7
#define LR_EVENT_MAX_PREFIX_EXCEEDED 8
#define LR_EVENT_MAX_PREFIX_THRESHOLD 9

/* MaxPrefixExceeded action ids (lr_event_t::action). */
#define LR_MAX_PREFIX_WARN 0
#define LR_MAX_PREFIX_TEARDOWN 1
#define LR_MAX_PREFIX_RESTART 2




/**
 * Maximum text length carried in one event (peer-state names, log
 * lines, protocol-error messages). Longer strings are truncated to
 * `LR_EVENT_TEXT_MAX - 1` bytes plus the NUL terminator; the full
 * text stays available through the Rust API.
 */
#define LR_EVENT_TEXT_MAX 128

/**
 * ORIGIN values (RFC 4271 §5.1.1).
 */
#define LR_ORIGIN_IGP 0

#define LR_ORIGIN_EGP 1

#define LR_ORIGIN_INCOMPLETE 2

/**
 * Route-map match condition kinds (`lr_match_t::kind`).
 */
#define LR_MATCH_PREFIX_IN 0

#define LR_MATCH_AS_PATH_IN 1

#define LR_MATCH_COMMUNITY_IN 2

#define LR_MATCH_PROTOCOL_IS 3

#define LR_MATCH_NEXT_HOP_IN 4

/**
 * Route-map set action kinds (`lr_set_t::kind`).
 */
#define LR_SET_LOCAL_PREF 0

#define LR_SET_MED 1

#define LR_SET_NEXT_HOP 2

#define LR_SET_PREPEND_AS 3

#define LR_SET_ADD_COMMUNITY 4

#define LR_SET_METRIC 5

#define LR_SET_TAG 6

/**
 * Route-map entry verdict (`lr_route_map_add_entry`).
 */
#define LR_VERDICT_CONTINUE 0

#define LR_VERDICT_PERMIT 1

#define LR_VERDICT_DENY 2

/**
 * `lr_route_map_evaluate` verdict output.
 */
#define LR_EVAL_DENY 0

#define LR_EVAL_PERMIT 1

#define LR_EVAL_FALLTHROUGH -1

/**
 * Validation outcome constants (`lr_roa_store_validate` out param).
 */
#define LR_ROA_VALID 0

#define LR_ROA_NOT_FOUND 1

#define LR_ROA_INVALID 2

/**
 * Area kind ids shared by `lr_router_add_ospf_session_ext`. The stub
 * and NSSA kinds carry a `default_metric` (the border-router-injected
 * default route, RFC 2328 §3.6 / RFC 3101 §2.7); the `*_NO_SUMMARY`
 * variants suppress inter-area summaries ("totally stubby / totally
 * NSSA").
 */
#define LR_AREA_NORMAL 0

#define LR_AREA_STUB 1

#define LR_AREA_STUB_NO_SUMMARY 2

#define LR_AREA_NSSA 3

#define LR_AREA_NSSA_NO_SUMMARY 4

/**
 * Interface network-type ids (RFC 2328 §9.1), shared by
 * `lr_router_add_ospf_session_ext`.
 */
#define LR_NET_PTP 0

#define LR_NET_BROADCAST 1

/**
 * OSPF protocol version selector for `lr_router_add_ospf_session_ext`.
 */
#define LR_OSPF_V2 2

#define LR_OSPF_V3 3

/**
 * Rust-allocated byte slice that the embedder owns and must free.
 */
typedef struct lr_bytes_t {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} lr_bytes_t;

/**
 * One IPv4/IPv6 prefix (embedder-side). IPv4 addresses go in the
 * first four bytes of `addr` with `is_ipv6 = 0`; IPv6 uses all
 * sixteen bytes with `is_ipv6 = 1` — the same convention as
 * `lr_roa_entry_t`.
 */
typedef struct lr_prefix_t {
  uint8_t addr[16];
  uint8_t is_ipv6;
  uint8_t prefix_len;
} lr_prefix_t;

/**
 * Opaque router handle. C side never touches internals.
 */
typedef struct OpaqueRouter {
  uint8_t _private[0];
} OpaqueRouter;

typedef struct OpaqueRouter *lr_router_t;

/**
 * One serialized router event. Only the fields meaningful for `kind`
 * are populated; the rest are zero. `prefix` carries IPv4 in its
 * first four bytes with `is_ipv6 == 0`, IPv6 in all sixteen with
 * `is_ipv6 == 1`. `text` is NUL-terminated.
 */
typedef struct lr_event_t {
  /**
   * Which event this is ([`lr_event_kind_t`], also published as the
   * `LR_EVENT_*` defines in the header).
   */
  int32_t kind;
  /**
   * The session the event relates to (0 when none).
   */
  uint64_t session;
  /**
   * The prefix (RouteInstalled / RouteWithdrawn / Prefix* events).
   */
  uint8_t prefix[16];
  /**
   * Prefix length in bits.
   */
  uint8_t prefix_len;
  /**
   * 1 when `prefix` carries an IPv6 address.
   */
  uint8_t is_ipv6;
  /**
   * The Add-Path identifier of the installed/withdrawn path.
   */
  uint32_t path_id;
  /**
   * MaxPrefix events: the current Adj-RIB-In size.
   */
  uint32_t count;
  /**
   * MaxPrefix events: the configured ceiling.
   */
  uint32_t limit;
  /**
   * MaxPrefixThreshold: the crossing percentage.
   */
  uint32_t pct;
  /**
   * MaxPrefixExceeded: 0 = warn, 1 = teardown, 2 = restart.
   */
  int32_t action;
  /**
   * Peer state, log line or error message, NUL-terminated
   * (truncated at [`LR_EVENT_TEXT_MAX`] bytes).
   */
  uint8_t text[LR_EVENT_TEXT_MAX];
} lr_event_t;

/**
 * Opaque damping handle. Wraps a boxed `Arc<Mutex<DampingTable>>`
 * shared with the hook installed on the router.
 */
typedef struct OpaqueDamping {
  uint8_t _private[0];
} OpaqueDamping;

typedef struct OpaqueDamping *lr_damping_t;

/**
 * RFC 2439 §4.7 damping tunables. Mirrors
 * `lr_damping::DampingConfig` field-for-field.
 */
typedef struct lr_damping_config_t {
  uint32_t additive_incr;
  uint32_t suppress_threshold;
  uint32_t reuse_threshold;
  uint32_t upper_limit;
  uint64_t decay_interval_s;
  double decay_factor_active;
  double decay_factor_withdrawn;
} lr_damping_config_t;

/**
 * Opaque route handle. Boxes a real `lr_core::rib::Route` so filter
 * and route-map evaluation run against the same data model the
 * library uses internally.
 */
typedef struct OpaqueRoute {
  uint8_t _private[0];
} OpaqueRoute;

typedef struct OpaqueRoute *lr_route_t;

/**
 * One RFC 4360 extended community, embedder-side.
 */
typedef struct lr_ext_comm_t {
  uint8_t kind;
  uint8_t subtype;
  uint32_t global;
  uint16_t local;
} lr_ext_comm_t;

/**
 * Opaque prefix-list handle (`lr_policy::PrefixList`).
 */
typedef struct OpaquePrefixList {
  uint8_t _private[0];
} OpaquePrefixList;

typedef struct OpaquePrefixList *lr_prefix_list_t;

/**
 * Opaque route-map handle (`lr_policy::RouteMap`).
 */
typedef struct OpaqueRouteMap {
  uint8_t _private[0];
} OpaqueRouteMap;

typedef struct OpaqueRouteMap *lr_route_map_t;

/**
 * One route-map match condition.
 */
typedef struct lr_match_t {
  /**
   * [`LR_MATCH_*`](LR_MATCH_PREFIX_IN) kind.
   */
  uint8_t kind;
  /**
   * List id for the `*_IN` kinds (as returned by the
   * `lr_resolver_add_*` registrations).
   */
  uint32_t list_id;
  /**
   * [`LrProtocol`] id for [`LR_MATCH_PROTOCOL_IS`].
   */
  uint8_t protocol;
} lr_match_t;

/**
 * One route-map set action.
 */
typedef struct lr_set_t {
  /**
   * [`LR_SET_*`](LR_SET_LOCAL_PREF) kind.
   */
  uint8_t kind;
  /**
   * IPv6 flag for [`LR_SET_NEXT_HOP`].
   */
  uint8_t is_ipv6;
  /**
   * Address for [`LR_SET_NEXT_HOP`] (first 4 bytes for IPv4).
   */
  uint8_t addr[16];
  /**
   * Payload: LOCAL_PREF / MED / the AS for PREPEND_AS / the ASN for
   * ADD_COMMUNITY / METRIC / TAG.
   */
  uint32_t value;
  /**
   * Community value for [`LR_SET_ADD_COMMUNITY`].
   */
  uint16_t value2;
} lr_set_t;

/**
 * Opaque policy resolver handle (`lr_policy::PolicySet`): the named
 * registry of prefix-lists / AS-path filters / community lists that
 * route-map match conditions resolve against.
 */
typedef struct OpaqueResolver {
  uint8_t _private[0];
} OpaqueResolver;

typedef struct OpaqueResolver *lr_resolver_t;

/**
 * One FRR-dialect AS-path access-list filter.
 */
typedef struct lr_as_path_filter_t {
  /**
   * NUL-terminated pattern (`_65001_`, `^65001$`, ...). Borrowed for
   * the duration of the `lr_resolver_add_as_path_list` call only.
   */
  const char *pattern;
  /**
   * Non-zero: permit, zero: deny.
   */
  uint8_t permit;
} lr_as_path_filter_t;

/**
 * One community-list entry (RFC 1997 standard list).
 */
typedef struct lr_community_entry_t {
  /**
   * Packed `asn << 16 | value` communities. Borrowed for the
   * duration of the `lr_resolver_add_community_list` call only.
   */
  const uint64_t *communities;
  uintptr_t count;
  /**
   * Non-zero: permit, zero: deny.
   */
  uint8_t permit;
} lr_community_entry_t;

/**
 * Opaque ROA store handle. C side never touches internals.
 */
typedef struct OpaqueRoaStore {
  uint8_t _private[0];
} OpaqueRoaStore;

typedef struct OpaqueRoaStore *lr_roa_store_t;

/**
 * One ROA entry for the FFI surface. IPv4 addresses go in the first
 * four bytes of `addr` with `is_ipv6 = 0`; IPv6 uses all sixteen
 * bytes with `is_ipv6 = 1`. `max_length` must be >= `prefix_len`
 * (and <= 32 / 128) — malformed entries fail the whole batch with
 * `LrError::Other` semantics (rc != 0) and never reach the store.
 */
typedef struct lr_roa_entry_t {
  /**
   * Address bytes (v4 in the low four bytes, zero-padded).
   */
  uint8_t addr[16];
  /**
   * 0 = IPv4, anything else = IPv6.
   */
  uint8_t is_ipv6;
  /**
   * Prefix length (0..=32 for v4, 0..=128 for v6).
   */
  uint8_t prefix_len;
  /**
   * Maximum authorized prefix length.
   */
  uint8_t max_length;
  /**
   * Authorized origin AS. AS 0 marks the blackhole range
   * (RFC 6483 §4).
   */
  uint32_t asn;
} lr_roa_entry_t;

/**
 * One record delta for `lr_roa_store_apply_deltas` — the wire shape
 * of an RTR Prefix PDU (RFC 8210 §5.6/§5.7).
 */
typedef struct lr_roa_delta_t {
  /**
   * 0 = withdraw, anything else = announce.
   */
  uint8_t announce;
  /**
   * The record the delta applies to.
   */
  struct lr_roa_entry_t entry;
} lr_roa_delta_t;

/**
 * Free an `lr_bytes_t` previously returned from any `lr_*` function. Safe to
 * call with a NULL pointer.
 *
 * # Safety
 * The pointer must have been produced by an `lr_*` function.
 */
void lr_bytes_free(struct lr_bytes_t *b);

/**
 * Length of an `lr_bytes_t`.
 */
uintptr_t lr_bytes_len(const struct lr_bytes_t *b);

/**
 * Pointer to the data of an `lr_bytes_t`. NULL if `b` is NULL.
 */
const uint8_t *lr_bytes_ptr(const struct lr_bytes_t *b);

/**
 * Decode one BGP message from `data`. Returns 0 on success (and writes a
 * `lr_bytes_t` containing the message type byte at offset 0 + body to
 * `out`). Negative on error.
 */
int32_t lr_bgp_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Encode a KEEPALIVE message (RFC 4271 §4.4). Part of the D5.4
 * encoder surface: see also [`lr_bgp_encode_open`],
 * [`lr_bgp_encode_notification`], [`lr_bgp_encode_update_withdraw_v4`]
 * and [`lr_bgp_encode_update_announce_v4`].
 */
int32_t lr_bgp_encode_keepalive(struct lr_bytes_t *out);

/**
 * Encode an OPEN message (RFC 4271 §4.2, ROADMAP-v3 D5.4): version 4,
 * the given AS, hold time and BGP identifier. When `as4` is non-zero
 * the RFC 6793 four-octet-AS capability (code 65) is appended with the
 * full 32-bit AS — an AS above 65535 then travels as AS_TRANS (23456)
 * in the 16-bit field per RFC 4893 §7. An AS above 65535 with `as4`
 * unset is rejected (it cannot be represented on the wire).
 *
 * Hold time 0 (use the negotiated default) or >= 3 per RFC 4271 §4.2;
 * the illegal 1-2 second values are rejected up front.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `bgp_id` must point to 4 readable bytes.
 */
int32_t lr_bgp_encode_open(uint32_t my_as,
                           uint16_t hold_time,
                           const uint8_t *bgp_id,
                           uint8_t as4,
                           struct lr_bytes_t *out);

/**
 * Encode a NOTIFICATION message (RFC 4271 §4.5): the error code, the
 * subcode and the optional data payload (NULL when `data_len` is 0).
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `data` must point to `data_len` readable bytes (NULL only when
 * `data_len` is 0).
 */
int32_t lr_bgp_encode_notification(uint8_t error_code,
                                   uint8_t error_subcode,
                                   const uint8_t *data,
                                   uintptr_t data_len,
                                   struct lr_bytes_t *out);

/**
 * Encode a withdraw-only UPDATE (RFC 4271 §4.3): every listed IPv4
 * prefix goes into the withdrawn-routes section; no path attributes,
 * no NLRI. Returns 0 on success, negative on error.
 *
 * # Safety
 * `prefixes` must point to `n_prefixes` readable `lr_prefix_t` values.
 */
int32_t lr_bgp_encode_update_withdraw_v4(const struct lr_prefix_t *prefixes,
                                         uintptr_t n_prefixes,
                                         struct lr_bytes_t *out);

/**
 * Encode an announcement UPDATE (RFC 4271 §4.3): ORIGIN + AS_PATH +
 * NEXT_HOP attributes and the IPv4 prefixes in the NLRI section.
 *
 * `origin` selects the ORIGIN value (0 = IGP, 1 = EGP, 2 = INCOMPLETE;
 * anything else is rejected). `as_path` is an AS_SEQUENCE in wire order
 * (the origin AS first); with `as4` set the segments use the RFC 6793
 * four-octet encoding. An empty AS_PATH (locally originated) is legal.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `prefixes` must point to `n_prefixes` readable `lr_prefix_t` values,
 * `next_hop` to 4 readable bytes and `as_path` to `as_path_len` readable
 * `uint32_t` values.
 */
int32_t lr_bgp_encode_update_announce_v4(const struct lr_prefix_t *prefixes,
                                         uintptr_t n_prefixes,
                                         const uint8_t *next_hop,
                                         const uint32_t *as_path,
                                         uintptr_t as_path_len,
                                         uint8_t origin,
                                         uint8_t as4,
                                         struct lr_bytes_t *out);

int32_t lr_ospf_decode_v2(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

int32_t lr_babel_decode(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Get the last error message. Returned string is NUL-terminated UTF-8.
 *
 * # Safety
 * The returned pointer is valid until the next FFI call on this thread.
 */
const char *lr_last_error(void);

/**
 * ABI version packed as u32. Compare to `lr_core::ABI_VERSION`.
 */
uint32_t lr_abi_version(void);

/**
 * Poll up to `cap` router events into `out` (ROADMAP-v3 D5.5):
 * peer-state changes, route installs/withdrawals, advertisements and
 * retractions, logs, protocol errors and the maximum-prefix signals.
 * Returns the number of events written; 0 means the queue is empty
 * for now. Events beyond the buffer are requeued — nothing is lost,
 * the next call delivers them first. Negative on error.
 *
 * Transport-plane events (`SendBytes`, `TimerFired`) are consumed
 * and dropped by the poll: outgoing bytes ride
 * [`crate::handle`]`::drain_output`, timers are internal.
 *
 * # Safety
 * `out` must point to `cap` writable `lr_event_t` values when `cap`
 * is positive.
 */
int32_t lr_router_poll_events(lr_router_t r, struct lr_event_t *out, int32_t cap);

/**
 * Install one redistribution pipe on the router.
 *
 * `source` / `target` are [`LrProtocol`] values, `metric_policy` a
 * [`LrMetricPolicy`]. `has_tag` gates `tag` (any non-zero installs
 * the tag). `allow` / `allow_count` carry an optional allow-list of
 * prefixes (NULL / 0 = redistribute everything). Returns 0 on
 * success, -1 on a null argument, -2 on an invalid router handle,
 * -3 on a malformed argument (unknown protocol id, bad prefix
 * length), and [`LR_ERR_PANIC`] if the body panics.
 *
 * # Safety
 * `r` must be a live router handle. `allow` (when non-null) must
 * point to `allow_count` readable `lr_prefix_t` values.
 */
int32_t lr_router_add_redistribution_pipe(lr_router_t r,
                                          int32_t source,
                                          int32_t target,
                                          int32_t metric_policy,
                                          uint32_t metric,
                                          int32_t has_tag,
                                          uint32_t tag,
                                          const struct lr_prefix_t *allow,
                                          uintptr_t allow_count);

/**
 * Register an RFC 4271 §9.2.2.2 aggregate. The aggregate is
 * originated while a more-specific exists and withdrawn when the
 * last one disappears. Returns 0 on success, -1 / -2 / -3 on
 * null / invalid-handle / malformed-prefix.
 *
 * # Safety
 * `r` must be a live router handle; `prefix` must be a readable
 * `lr_prefix_t`.
 */
int32_t lr_router_add_aggregate(lr_router_t r, const struct lr_prefix_t *prefix);

/**
 * Withdraw a previously registered aggregate. Removing an unknown
 * prefix is a no-op that still returns 0 (the router treats it the
 * same way).
 *
 * # Safety
 * See [`lr_router_add_aggregate`].
 */
int32_t lr_router_remove_aggregate(lr_router_t r, const struct lr_prefix_t *prefix);

/**
 * Install the RFC 2439 damping import hook with the supplied
 * tunables and return a shared [`lr_damping_t`] handle. The embedder
 * drives decay with [`lr_damping_decay`] (the in-process analogue of
 * the daemon's `lr-damping-decay` thread) and frees the handle with
 * [`lr_damping_destroy`]. Installing damping twice replaces nothing —
 * the second hook simply chains after the first; call this once per
 * router.
 *
 * Returns NULL on null/invalid arguments (the last-error string says
 * which) and the handle otherwise.
 *
 * # Safety
 * `r` must be a live router handle; `cfg` must be a readable
 * `lr_damping_config_t`.
 */
lr_damping_t lr_router_set_damping(lr_router_t r, const struct lr_damping_config_t *cfg);

/**
 * Drive one damping decay pass at wall-clock `now_s` (seconds).
 * Returns the number of prefixes that re-emerged from suppression
 * (>= 0), or negative error codes on null / invalid handles.
 *
 * # Safety
 * `d` must be a live damping handle from [`lr_router_set_damping`].
 */
int32_t lr_damping_decay(struct OpaqueDamping *d, uint64_t now_s);

/**
 * Free a damping handle. The hook installed on the router keeps its
 * own `Arc`, so damping continues until the router is destroyed;
 * destroying the handle only releases the embedder's decay access.
 *
 * # Safety
 * `d` must be null or a handle returned by [`lr_router_set_damping`]
 * that has not been destroyed yet, and must not be used afterwards.
 */
void lr_damping_destroy(struct OpaqueDamping *d);

/**
 * Create a route handle for an IPv4 prefix. `protocol` is an
 * [`LrProtocol`] id. Returns NULL on a malformed prefix length or
 * unknown protocol id (the last-error string says which).
 *
 * # Safety
 * `octets` must point to 4 readable bytes.
 */
lr_route_t lr_route_new_v4(const uint8_t *octets, uint8_t prefix_len, int32_t protocol);

/**
 * Create a route handle for an IPv6 prefix. See
 * [`lr_route_new_v4`] for the contract.
 *
 * # Safety
 * `octets` must point to 16 readable bytes.
 */
lr_route_t lr_route_new_v6(const uint8_t *octets, uint8_t prefix_len, int32_t protocol);

/**
 * Free a route handle. NULL is a no-op.
 *
 * # Safety
 * `route` must be null or a handle returned by `lr_route_new_*` that
 * has not been freed yet, and must not be used afterwards.
 */
void lr_route_free(lr_route_t route);

/**
 * Set the route's next hop (RFC 4271 §5.1.3). `addr` carries the
 * IPv4 octets in the first four bytes when `is_ipv6` is 0. Returns
 * 0, -1 on a null argument.
 *
 * # Safety
 * `addr` must point to 4 (v4) / 16 (v6) readable bytes.
 */
int32_t lr_route_set_next_hop(lr_route_t route, const uint8_t *addr, int32_t is_ipv6);

/**
 * Read the route's next hop into `out` (16 bytes, IPv4 in the first
 * four) and its family into `out_is_ipv6`. Returns 0 when present,
 * 1 when absent, -1 on a null argument.
 *
 * # Safety
 * `out` must be writable for 16 bytes; `out_is_ipv6` writable for one
 * `i32`.
 */
int32_t lr_route_next_hop(lr_route_t route, uint8_t *out, int32_t *out_is_ipv6);

/**
 * Set the BGP LOCAL_PREF (RFC 4271 §5.1.5). Returns 0 / -1.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_set_local_pref(lr_route_t route, uint32_t value);

/**
 * Read LOCAL_PREF into `out`. Returns 0 present, 1 absent, -1 null.
 *
 * # Safety
 * `out` must be writable.
 */
int32_t lr_route_local_pref(lr_route_t route, uint32_t *out);

/**
 * Set the BGP MULTI_EXIT_DISC (RFC 4271 §4.2.4). 0 / -1.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_set_med(lr_route_t route, uint32_t value);

/**
 * Read MULTI_EXIT_DISC. 0 present, 1 absent, -1 null.
 *
 * # Safety
 * `out` must be writable.
 */
int32_t lr_route_med(lr_route_t route, uint32_t *out);

/**
 * Set the BGP ORIGIN (RFC 4271 §5.1.1): [`LR_ORIGIN_IGP`],
 * [`LR_ORIGIN_EGP`] or [`LR_ORIGIN_INCOMPLETE`]. Returns 0, -1 null,
 * -3 unknown origin value.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_set_origin(lr_route_t route, uint8_t origin);

/**
 * Read ORIGIN into `out`. 0 present, 1 absent, -1 null.
 *
 * # Safety
 * `out` must be writable.
 */
int32_t lr_route_origin(lr_route_t route, uint8_t *out);

/**
 * Replace the AS_PATH with a flat sequence (RFC 4271 §4.3). An empty
 * sequence drops the attribute. 0 ok, -1 null.
 *
 * # Safety
 * `asns` must point to `count` readable `u32`s when non-null.
 */
int32_t lr_route_set_as_path(lr_route_t route, const uint32_t *asns, uintptr_t count);

/**
 * Read the AS_PATH's flat sequence. Call with `out = NULL` to get the
 * required length; with a buffer, returns the number of ASes written.
 * Negative on null handle / buffer smaller than needed.
 *
 * # Safety
 * `out` (when non-null) must be writable for `cap` `u32`s.
 */
int64_t lr_route_as_path(lr_route_t route, uint32_t *out, uintptr_t cap);

/**
 * Append one standard community (RFC 1997 §4). The ASN must fit 16
 * bits — 4-octet-AS communities ride LARGE_COMMUNITIES (RFC 8097).
 * 0 ok, -1 null, -3 ASN > 0xFFFF.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_add_community(lr_route_t route, uint32_t asn, uint16_t value);

/**
 * Replace the whole standard COMMUNITIES attribute from packed
 * `asn << 16 | value` items. An empty set drops the attribute.
 *
 * # Safety
 * `items` must point to `count` readable `u64`s when non-null.
 */
int32_t lr_route_set_communities(lr_route_t route, const uint64_t *items, uintptr_t count);

/**
 * Read the standard communities as packed `asn << 16 | value`.
 * `out = NULL` → required length; otherwise the count written.
 *
 * # Safety
 * `out` (when non-null) must be writable for `cap` `u64`s.
 */
int64_t lr_route_communities(lr_route_t route, uint64_t *out, uintptr_t cap);

/**
 * Append one large community (RFC 8097).
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_add_large_community(lr_route_t route,
                                     uint32_t global_admin,
                                     uint32_t local_data1,
                                     uint32_t local_data2);

/**
 * Replace the whole LARGE_COMMUNITIES attribute from flat triples.
 *
 * # Safety
 * `triples` must point to `count * 3` readable `u32`s when non-null.
 */
int32_t lr_route_set_large_communities(lr_route_t route, const uint32_t *triples, uintptr_t count);

/**
 * Read the large communities as flat triples. `out = NULL` →
 * required `u32` count (3 * entries); otherwise the count written.
 *
 * # Safety
 * `out` (when non-null) must be writable for `cap` `u32`s.
 */
int64_t lr_route_large_communities(lr_route_t route, uint32_t *out, uintptr_t cap);

/**
 * Append one extended community (RFC 4360).
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_add_ext_community(lr_route_t route,
                                   uint8_t kind,
                                   uint8_t subtype,
                                   uint32_t global,
                                   uint16_t local);

/**
 * Replace the whole EXTENDED_COMMUNITIES attribute.
 *
 * # Safety
 * `items` must point to `count` readable `lr_ext_comm_t`s when
 * non-null.
 */
int32_t lr_route_set_ext_communities(lr_route_t route,
                                     const struct lr_ext_comm_t *items,
                                     uintptr_t count);

/**
 * Read the extended communities. `out = NULL` → required length,
 * otherwise the count written.
 *
 * # Safety
 * `out` (when non-null) must be writable for `cap` `lr_ext_comm_t`s.
 */
int64_t lr_route_ext_communities(lr_route_t route, struct lr_ext_comm_t *out, uintptr_t cap);

/**
 * Set the route's metric (the cross-protocol preference metric).
 * 0 / -1.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_set_metric(lr_route_t route, uint32_t value);

/**
 * Read the route's metric. 0 / -1.
 *
 * # Safety
 * `out` must be writable.
 */
int32_t lr_route_metric(lr_route_t route, uint32_t *out);

/**
 * Set the operator route tag (`None` when `has_tag` is 0). 0 / -1.
 *
 * # Safety
 * `route` must be a live handle.
 */
int32_t lr_route_set_tag(lr_route_t route, int32_t has_tag, uint32_t tag);

/**
 * Read the route tag. 0 present, 1 absent, -1 null.
 *
 * # Safety
 * `out` must be writable.
 */
int32_t lr_route_tag(lr_route_t route, uint32_t *out);

/**
 * Create an empty prefix-list. NULL on panic.
 */
lr_prefix_list_t lr_prefix_list_new(void);

/**
 * Free a prefix-list. NULL is a no-op.
 *
 * # Safety
 * `list` must be null or a handle from `lr_prefix_list_new` that has
 * not been freed or consumed by `lr_resolver_add_prefix_list`.
 */
void lr_prefix_list_free(lr_prefix_list_t list);

/**
 * Append one entry: `prefix` with the ge/le length window (FRR
 * `ge`/`le`; `le = 255` means no upper bound) and `permit` (non-zero
 * = permit). First matching entry decides; no match denies.
 * 0 ok, -1 null, -3 malformed prefix.
 *
 * # Safety
 * `list` must be a live handle; `prefix` a readable `lr_prefix_t`.
 */
int32_t lr_prefix_list_add(lr_prefix_list_t list,
                           const struct lr_prefix_t *prefix,
                           uint8_t ge,
                           uint8_t le,
                           int32_t permit);

/**
 * Evaluate the list against `prefix`: 1 = permit, 0 = deny (implicit
 * deny included), -1 null.
 *
 * # Safety
 * `list` must be a live handle; `prefix` a readable `lr_prefix_t`.
 */
int32_t lr_prefix_list_match(lr_prefix_list_t list, const struct lr_prefix_t *prefix);

/**
 * Create an empty route-map. NULL on panic.
 */
lr_route_map_t lr_route_map_new(void);

/**
 * Free a route-map. NULL is a no-op.
 *
 * # Safety
 * `map` must be null or a handle from `lr_route_map_new` that has not
 * been freed.
 */
void lr_route_map_free(lr_route_map_t map);

/**
 * Append one entry: all `matches` must hold, then all `sets` apply
 * and `verdict` decides ([`LR_VERDICT_CONTINUE`] falls through to the
 * next entry). Entries are tried in insertion order. 0 ok, -1 null,
 * -3 malformed match/set or prefix length.
 *
 * # Safety
 * `map` must be a live handle; the arrays readable for `n_matches` /
 * `n_sets` items when non-null.
 */
int32_t lr_route_map_add_entry(lr_route_map_t map,
                               const struct lr_match_t *matches,
                               uintptr_t n_matches,
                               const struct lr_set_t *sets,
                               uintptr_t n_sets,
                               int32_t verdict);

/**
 * FRR route-map evaluation over a live route handle: the first
 * matching entry applies its sets and its verdict lands in `out`
 * ([`LR_EVAL_PERMIT`] / [`LR_EVAL_DENY`] / [`LR_EVAL_FALLTHROUGH`]).
 * Mutations are visible to subsequent `lr_route_*` reads.
 * 0 ok, -1 null, -2 invalid handle.
 *
 * `resolver` may be NULL: then every list-backed match fails
 * (fail-closed, FRR unknown-list semantics).
 *
 * # Safety
 * `map` / `route` must be live handles; `resolver` null or live.
 */
int32_t lr_route_map_evaluate(lr_route_map_t map,
                              lr_route_t route,
                              lr_resolver_t resolver,
                              int32_t *out);

/**
 * Create an empty policy resolver. NULL on panic.
 */
lr_resolver_t lr_resolver_new(void);

/**
 * Free a resolver. Registered policy objects go with it.
 *
 * # Safety
 * `resolver` must be null or a handle from `lr_resolver_new` that has
 * not been freed.
 */
void lr_resolver_free(lr_resolver_t resolver);

/**
 * Register the prefix-list under `name` (NUL-terminated). The list is
 * COPIED into the resolver; the caller keeps ownership of the handle.
 * Returns the numeric list id for `lr_match_t.list_id` (>= 0), or
 * -1/-3 on null/malformed.
 *
 * # Safety
 * `resolver` must be live; `name` a readable NUL-terminated string;
 * `list` a live handle.
 */
int32_t lr_resolver_add_prefix_list(lr_resolver_t resolver,
                                    const char *name,
                                    lr_prefix_list_t list);

/**
 * Register an AS-path access-list (FRR dialect) under `name`. Returns
 * the list id, or -1/-3.
 *
 * # Safety
 * `resolver` must be live; `filters` readable for `count` items, each
 * `pattern` a readable NUL-terminated string.
 */
int32_t lr_resolver_add_as_path_list(lr_resolver_t resolver,
                                     const char *name,
                                     const struct lr_as_path_filter_t *filters,
                                     uintptr_t count);

/**
 * Register a standard community list (RFC 1997) under `name`. Returns
 * the list id, or -1/-3.
 *
 * # Safety
 * `resolver` must be live; `entries` readable for `count` items, each
 * `communities` array readable for its `count`.
 */
int32_t lr_resolver_add_community_list(lr_resolver_t resolver,
                                       const char *name,
                                       const struct lr_community_entry_t *entries,
                                       uintptr_t count);

/**
 * Create an empty ROA store. NULL on panic (last-error set).
 */
lr_roa_store_t lr_roa_store_new(void);

/**
 * Free a ROA store. NULL is a no-op. Must not run concurrently with
 * any other call on the same handle.
 *
 * # Safety
 * `s` must have been produced by [`lr_roa_store_new`] and must not
 * be freed twice.
 */
void lr_roa_store_free(lr_roa_store_t s);

/**
 * Atomically replace the **static** layer (local configuration) with
 * `len` entries. RTR-learned entries are preserved. Returns 0 on
 * success; -6 (`Other`) with the last-error string set when any
 * entry is malformed — in that case nothing is applied.
 *
 * # Safety
 * `s` must be a live store handle; `entries` must point at `len`
 * readable `lr_roa_entry_t`s (NULL with len 0 clears the layer).
 */
int32_t lr_roa_store_replace_static(lr_roa_store_t s,
                                    const struct lr_roa_entry_t *entries,
                                    uintptr_t len);

/**
 * Apply a batch of RTR deltas atomically (one completed sync).
 * Duplicates coalesce and unknown withdrawals are no-ops — the RFC
 * 8210 §5.6 / §12 code-6 semantics live in the set math. Returns 0
 * on success, -6 with last-error on a malformed entry (nothing
 * applied), -1/-4 as usual.
 *
 * # Safety
 * `s` must be a live store handle; `deltas` must point at `len`
 * readable `lr_roa_delta_t`s (NULL with len 0 is a no-op).
 */
int32_t lr_roa_store_apply_deltas(lr_roa_store_t s,
                                  const struct lr_roa_delta_t *deltas,
                                  uintptr_t len);

/**
 * Withdraw every RTR-learned entry — the RFC 8210 §6 data-expiry and
 * cache-change response. Static entries survive.
 *
 * # Safety
 * `s` must be a live store handle.
 */
int32_t lr_roa_store_clear_rtr(lr_roa_store_t s);

/**
 * Current merged entry count (static + RTR layers, deduplicated).
 * 0 on NULL / panic.
 *
 * # Safety
 * `s` must be NULL or a live store handle.
 */
uintptr_t lr_roa_store_len(lr_roa_store_t s);

/**
 * RFC 6811 §2 validation against the current snapshot. Writes
 * `LR_ROA_VALID` / `LR_ROA_NOT_FOUND` / `LR_ROA_INVALID` to
 * `out_state`. A NULL `origin_as` (no AS_PATH) validates as
 * `LR_ROA_NOT_FOUND` — a route without an origin AS is not covered
 * by any ROA.
 *
 * # Safety
 * `s` must be a live store handle; `addr_v4` (4 bytes) or `addr_v6`
 * (16 bytes) must be readable; `out_state` must be writable.
 */
int32_t lr_roa_store_validate(lr_roa_store_t s,
                              const uint8_t *addr_v4,
                              const uint8_t *addr_v6,
                              uint8_t prefix_len,
                              uint32_t origin_as,
                              uint8_t has_origin_as,
                              uint8_t *out_state);

/**
 * Create a new router instance.
 */
lr_router_t lr_router_new(void);

/**
 * Destroy a router instance. Safe to call with NULL.
 *
 * # Safety
 * `r` must have been returned by `lr_router_new` and not yet destroyed.
 */
void lr_router_destroy(lr_router_t r);

/**
 * Add a BGP session. Returns 0 on success, negative on error. The session
 * handle is written to `out_handle`.
 *
 * Graceful restart (RFC 4724) is enabled with a 120 s restart time;
 * Long-Lived Graceful Restart (RFC 9494) is disabled. Use
 * [`lr_router_add_bgp_session_ext`] to configure both.
 */
int32_t lr_router_add_bgp_session(lr_router_t r,
                                  uint32_t local_as,
                                  uint32_t peer_as,
                                  uint32_t local_bgp_id,
                                  uint16_t hold_time,
                                  uint16_t keepalive,
                                  uint8_t asn4,
                                  uint64_t *out_handle);

/**
 * Extended session creation with graceful-restart knobs.
 *
 * - `graceful_restart` / `gr_restart_time`: RFC 4724 advertisement and
 *   stale-route retention (seconds; restart time is clamped to 12 bits).
 * - `long_lived_gr` / `llgr_stale_time`: RFC 9494 Long-Lived Graceful
 *   Restart — LLGR requires GR per RFC 9494 §4.1, so when
 *   `long_lived_gr` is set with `graceful_restart` clear the LLGR
 *   capability is not advertised.
 * - `llgr_max_stale_time`: optional local cap (seconds) on the stale time
 *   received from the peer; 0 disables the cap (RFC 9494 §4.2).
 */
int32_t lr_router_add_bgp_session_ext(lr_router_t r,
                                      uint32_t local_as,
                                      uint32_t peer_as,
                                      uint32_t local_bgp_id,
                                      uint16_t hold_time,
                                      uint16_t keepalive,
                                      uint8_t asn4,
                                      uint8_t graceful_restart,
                                      uint16_t gr_restart_time,
                                      uint8_t long_lived_gr,
                                      uint32_t llgr_stale_time,
                                      uint32_t llgr_max_stale_time,
                                      uint64_t *out_handle);

/**
 * Push bytes from the peer transport into a session.
 *
 * # Safety
 * `bytes` must be a valid pointer to `len` bytes.
 */
int32_t lr_router_feed_input(lr_router_t r, uint64_t session, const uint8_t *bytes, uintptr_t len);

/**
 * Drain bytes from a session to send to the peer transport.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_drain_output(lr_router_t r, uint64_t session, struct lr_bytes_t *out);

/**
 * Advance the router clock.
 */
int32_t lr_router_tick(lr_router_t r, uint64_t now_ms);

/**
 * Start a session: drives the protocol FSM into operation (BGP:
 * ManualStart + TransportOpen). Call once the transport is connected.
 */
int32_t lr_router_start_session(lr_router_t r, uint64_t session);

/**
 * Set the per-prefix RFC 4271 MRAI interval for a BGP session.
 *
 * A zero interval disables batching and flushes any pending UPDATEs.
 */
int32_t lr_router_set_mrai(lr_router_t r, uint64_t session, uint64_t interval_ms);

/**
 * Enable or disable RFC 7911 Add-Path on one BGP session.
 *
 * Must be called after `lr_router_add_bgp_session*` and before
 * `lr_router_start_session` — the capability is negotiated in OPEN.
 * `enabled` is 0 (off) or non-zero (on).
 */
int32_t lr_router_set_add_path(lr_router_t r, uint64_t session, uint8_t enabled);

/**
 * Set how many paths per prefix the RFC 7911 decision process keeps in
 * Loc-RIB and advertises to Add-Path peers (router-wide).
 *
 * Values below 1 are clamped to 1 (single-path). Takes effect for
 * sessions whose Add-Path capability was negotiated.
 */
int32_t lr_router_set_add_path_max_paths(lr_router_t r, uint32_t max_paths);

/**
 * Enable or disable the RFC 8212 default eBGP route behaviors
 * (router-wide).
 *
 * When enabled, an external BGP session (eBGP or a confederation
 * boundary) with no explicit import policy declared via
 * `lr_router_set_session_policy` discards received routes, and one
 * with no export policy advertises nothing (RFC 8212 §3). `enabled`
 * is 0 (off — the RFC 4271 default-accept) or non-zero (on).
 */
int32_t lr_router_set_ebgp_requires_policy(lr_router_t r, uint8_t enabled);

/**
 * Enable or disable FRR `bgp enforce-first-as` (W2.2).
 *
 * When on, an UPDATE received from an external BGP peer (eBGP or a
 * confederation boundary) whose AS_PATH leftmost sequence segment's
 * first AS is not the peer's negotiated AS is rejected before the
 * Adj-RIB-In. When off (the default — `no bgp enforce-first-as`),
 * the route is admitted subject to the ordinary policy and safety
 * checks. `enabled` is 0 (off) or non-zero (on).
 */
int32_t lr_router_set_enforce_first_as(lr_router_t r, uint8_t enabled);

/**
 * Declare which directions of a BGP session carry an explicit policy
 * (RFC 8212 §3).
 *
 * `import`/`export` are 0 (no policy — the direction is subject to
 * the RFC 8212 default deny when enabled) or non-zero (explicit
 * policy attached; the policy itself runs through the hook chain).
 * Call after `lr_router_add_bgp_session*`; unknown handles fail with
 * -2 and set the last-error string.
 */
int32_t lr_router_set_session_policy(lr_router_t r,
                                     uint64_t session,
                                     uint8_t import,
                                     uint8_t export_);

/**
 * Configure RFC 5549 Extended Next-Hop on a BGP session.
 *
 * `tuples` points to `count` 5-byte records, each laid out as
 * `<NLRI AFI:2 (big-endian), NLRI SAFI:1, Nexthop AFI:2 (big-endian)>`.
 * The canonical tuple is `00 01 01 00 02` — IPv4 unicast NLRI resolved
 * over an IPv6 next-hop. Pass `count = 0` to clear the configuration.
 * (This is the FFI input layout, not the wire form: RFC 5549 §4
 * encodes the capability on the wire as 6-byte tuples with a 2-octet
 * SAFI — librouting performs that conversion internally.)
 *
 * Must be called after `lr_router_add_bgp_session*` and before
 * `lr_router_start_session` — the capability is negotiated in OPEN.
 *
 * `count` must not exceed [`MAX_EXT_NEXT_HOP_TUPLES`]; larger values are
 * rejected with -3 (the cap keeps `count * 5` free of overflow before the
 * caller's memory is read).
 *
 * # Safety
 * `tuples` must point to at least `count * 5` readable bytes when
 * `count > 0`.
 */
int32_t lr_router_set_extended_next_hop(lr_router_t r,
                                        uint64_t session,
                                        const uint8_t *tuples,
                                        uintptr_t count);

/**
 * Override the MP-BGP address families advertised in OPEN.
 *
 * `families` points to `count` 4-byte records, each laid out as
 * `<AFI:2 (big-endian), reserved:1, SAFI:1>` — the same encoding used
 * by the RFC 4760 multiprotocol capability. The two well-known values
 * are `00 01 00 01` (IPv4 unicast) and `00 02 00 01` (IPv6 unicast).
 *
 * Must be called before `lr_router_start_session`. Replaces the default
 * IPv4-unicast-only family list.
 *
 * `count` must not exceed [`MAX_MP_FAMILIES`]; larger values are rejected
 * with -3 (the cap keeps `count * 4` free of overflow before the caller's
 * memory is read).
 *
 * # Safety
 * `families` must point to at least `count * 4` readable bytes when
 * `count > 0`.
 */
int32_t lr_router_set_mp_families(lr_router_t r,
                                  uint64_t session,
                                  const uint8_t *families,
                                  uintptr_t count);

/**
 * Set the local source address for next-hop-self egress on a BGP session.
 *
 * `addr_family` is `1` for IPv4 (4 bytes) or `2` for IPv6 (16 bytes).
 * `addr_bytes` must point to the appropriate number of bytes. Must be
 * called before `lr_router_start_session`.
 *
 * # Safety
 * `addr_bytes` must point to 4 (IPv4) or 16 (IPv6) readable bytes.
 */
int32_t lr_router_set_local_address(lr_router_t r,
                                    uint64_t session,
                                    uint16_t addr_family,
                                    const uint8_t *addr_bytes,
                                    uintptr_t addr_len);

/**
 * Configure FRR `bgp default ipv4-unicast` (W2.1) for a BGP session.
 *
 * When `enabled` is non-zero (the default), IPv4 unicast is implicitly
 * active even when `lr_router_set_mp_families` did not list it. When
 * zero, IPv4 unicast must be added explicitly via
 * `lr_router_set_mp_families` to be active — the FRR
 * `no bgp default ipv4-unicast` posture. Must be called after
 * `lr_router_add_bgp_session*` and before `lr_router_start_session`;
 * unknown handles or already-established sessions fail with -2.
 */
int32_t lr_router_set_default_ipv4_unicast(lr_router_t r, uint64_t session, uint8_t enabled);

/**
 * Configure FRR `neighbor X allowas-in N` / BIRD `allow local as`
 * (W2.3) for a BGP session.
 *
 * `tolerance = 0` (the default) rejects any occurrence of the local
 * AS in a received AS_PATH (RFC 4271 §9.1.2.15). `N > 0` admits a
 * route whose AS_PATH contains the local AS up to N times (FRR
 * `allowas-in N`, default N=1). The special value `u32::MAX` admits
 * any number (FRR `allowas-any`). iBGP sessions are exempt
 * (FRR/BIRD scope the relaxation to eBGP). Must be called after
 * `lr_router_add_bgp_session*` and before `lr_router_start_session`;
 * unknown handles or already-established sessions fail with -2.
 */
int32_t lr_router_set_local_as_tolerance(lr_router_t r, uint64_t session, uint32_t tolerance);

/**
 * Configure FRR `neighbor X soft-reconfiguration inbound` (W2.4) for
 * a BGP session.
 *
 * When `enabled` is non-zero, the router retains the pre-policy
 * Adj-RIB-In for this session — the raw received routes before the
 * import hook chain runs — so [`lr_router_soft_reconfig_inbound`] can
 * re-evaluate the policy without re-fetching from the peer. Off by
 * default (FRR's default; the cost is duplicate RIB memory per peer).
 * Must be called after `lr_router_add_bgp_session*` and before
 * `lr_router_start_session`; unknown handles or already-established
 * sessions fail with -2.
 */
int32_t lr_router_set_soft_reconfig_inbound(lr_router_t r, uint64_t session, uint8_t enabled);

/**
 * FRR `clear ip bgp * soft in` (W2.4): re-evaluate the import policy
 * against the pre-policy Adj-RIB-In for `session`, replacing the
 * session's entries in the post-policy RIB with the re-imported
 * routes.
 *
 * Returns the number of routes re-evaluated (as a non-negative
 * integer), or a negative value on error (-1 for an invalid router
 * handle, -2 on unknown session handles). No-ops (returns 0) when
 * the session did not have `soft_reconfig_inbound` enabled — the
 * pre-policy RIB was not retained.
 */
int64_t lr_router_soft_reconfig_inbound(lr_router_t r, uint64_t session);

/**
 * Request an RFC 2918 route refresh from an established BGP peer.
 *
 * Returns 1 when a request was queued, 0 when the session has not negotiated
 * route refresh, and a negative value for invalid handles or inputs.
 */
int32_t lr_router_request_route_refresh(lr_router_t r,
                                        uint64_t session,
                                        uint16_t afi,
                                        uint8_t safi);

/**
 * Originate a local IPv4 route: `prefix_addr` is 4 bytes, `prefix_len` is
 * the prefix length, `next_hop` is 4 bytes or NULL. The route is injected
 * into Loc-RIB and advertised to all established BGP peers.
 *
 * `prefix_len` must be <= 32; larger values are rejected with -3 before any
 * NLRI is encoded (an out-of-range length would otherwise panic inside the
 * BGP NLRI encoder the first time the route is exported).
 *
 * # Safety
 * `prefix_addr` and `next_hop` (when non-NULL) must be valid pointers to
 * 4 readable bytes.
 */
int32_t lr_router_originate_v4(lr_router_t r,
                               const uint8_t *prefix_addr,
                               uint8_t prefix_len,
                               const uint8_t *next_hop);

/**
 * Originate an RFC 8277 labelled IPv4 BGP route (AFI=1, SAFI=4). The
 * label stack is supplied as a flat array of 20-bit label values; the
 * codec wraps each into a `Label` with TC=0, TTL=64, and sets the
 * bottom-of-stack bit on the last entry. Returns 0 on success, negative
 * on error.
 *
 * `prefix_len` must be <= 32 (see [`lr_router_originate_v4`]) and
 * `n_labels` must not exceed [`MAX_LABEL_STACK_DEPTH`].
 *
 * # Safety
 * `prefix_addr` and `next_hop` (when non-NULL) must point to 4 readable
 * bytes; `labels` must point to `n_labels` readable `uint32_t` values.
 */
int32_t lr_router_originate_labeled_v4(lr_router_t r,
                                       const uint8_t *prefix_addr,
                                       uint8_t prefix_len,
                                       const uint32_t *labels,
                                       uintptr_t n_labels,
                                       const uint8_t *next_hop);

/**
 * Originate an RFC 8277 labelled IPv6 BGP route (AFI=2, SAFI=4). See
 * [`lr_router_originate_labeled_v4`] for the label-stack semantics.
 *
 * `prefix_len` must be <= 128; larger values are rejected with -3 before
 * any NLRI is encoded.
 *
 * # Safety
 * `prefix_addr` and `next_hop` (when non-NULL) must point to 16 readable
 * bytes; `labels` must point to `n_labels` readable `uint32_t` values.
 */
int32_t lr_router_originate_labeled_v6(lr_router_t r,
                                       const uint8_t *prefix_addr,
                                       uint8_t prefix_len,
                                       const uint32_t *labels,
                                       uintptr_t n_labels,
                                       const uint8_t *next_hop);

/**
 * Originate a local IPv6 unicast route (AFI=2, SAFI=1): injects it into
 * Loc-RIB (ORIGIN=IGP, empty AS_PATH) and advertises it to established
 * MP-BGP peers. The v6 counterpart of [`lr_router_originate_v4`]; the
 * next-hop is carried by MP_REACH_NLRI on egress.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `prefix_addr` and `next_hop` (when non-NULL) must point to 16 readable
 * bytes.
 */
int32_t lr_router_originate_v6(lr_router_t r,
                               const uint8_t *prefix_addr,
                               uint8_t prefix_len,
                               const uint8_t *next_hop);

/**
 * Withdraw a locally originated IPv4 route (FRR `no network ...`): the
 * prefix leaves the originated set, the decision process re-runs (a
 * beaten peer path is restored; an empty set withdraws the prefix from
 * every session) and any redistribution-sourced copy is flushed.
 * Returns 0 when the route was withdrawn, **1 when the prefix was not
 * locally originated** (idempotent no-op, matching FRR/BIRD `no
 * network` on an absent statement — nothing changes), negative on
 * error.
 *
 * # Safety
 * `prefix_addr` must point to 4 readable bytes.
 */
int32_t lr_router_withdraw_v4(lr_router_t r, const uint8_t *prefix_addr, uint8_t prefix_len);

/**
 * Withdraw a locally originated IPv6 unicast route. See
 * [`lr_router_withdraw_v4`] for the semantics and return codes (0 =
 * withdrawn, 1 = not locally originated, negative = error).
 *
 * # Safety
 * `prefix_addr` must point to 16 readable bytes.
 */
int32_t lr_router_withdraw_v6(lr_router_t r, const uint8_t *prefix_addr, uint8_t prefix_len);

/**
 * Query the kernel's MPLS platform-labels capability (Linux only).
 * Returns the value of `/proc/sys/net/mpls/platform_labels` (0 when
 * MPLS routing is not enabled, 16 or 20 when it is). On non-Linux
 * platforms this always returns 0.
 */
uint32_t lr_mpls_platform_labels(void);

/**
 * Number of routes currently in Loc-RIB.
 */
int64_t lr_router_rib_len(lr_router_t r);

/**
 * Dump the Loc-RIB as a text table (one route per line). The caller owns
 * the returned bytes and must free them with `lr_bytes_free`.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_rib_dump(lr_router_t r, struct lr_bytes_t *out);

/**
 * Dump every session's operational summary as a text table (one line
 * per session: handle, kind, ASNs, state, establishment, peer BGP id,
 * negotiated hold time, Adj-RIB-In size). The caller owns the returned
 * bytes and must free them with `lr_bytes_free`.
 *
 * # Safety
 * `out` must point to a valid `lr_bytes_t` slot.
 */
int32_t lr_router_sessions_dump(lr_router_t r, struct lr_bytes_t *out);

/**
 * Add one ROA entry to the router's ROA table (RFC 6482 §3 /
 * RFC 6811 §2). The router uses the table when a route is
 * imported and `lr_router_set_roa_validate(r, 1)` is set; the
 * filter DSL's `roa.state` accessor reads the same table.
 *
 * Parameters:
 * - `r`: router handle (from [`lr_router_new`]).
 * - `prefix_v4` / `prefix_v6`: the authorized prefix's address
 *   bytes. For IPv4, pass the first 4 bytes of `prefix_v4` and
 *   leave `prefix_v6` NULL. For IPv6, pass the 16-byte IPv6
 *   address through `prefix_v6` and leave `prefix_v4` NULL.
 * - `prefix_len`: the prefix length (0..=32 for v4, 0..=128 for v6).
 * - `max_length`: the maximum authorized prefix length (>=
 *   `prefix_len`, <= family width). Pass `0` to default to the
 *   exact prefix length.
 * - `asn`: the authorized origin AS (u32). AS 0 marks a
 *   blackhole-range ROA (RFC 6483 §4); it never matches a real
 *   origin AS but produces `Invalid` for any route under the
 *   prefix.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `r` must be a valid `lr_router_t`. `prefix_v4` (when non-NULL)
 * must point at 4 readable bytes; `prefix_v6` (when non-NULL)
 * must point at 16 readable bytes.
 */
int32_t lr_router_add_roa_entry(lr_router_t r,
                                const uint8_t *prefix_v4,
                                const uint8_t *prefix_v6,
                                uint8_t prefix_len,
                                uint8_t max_length,
                                uint32_t asn);

/**
 * Toggle RFC 6811 §2 prefix-origin validation on (1) or off (0).
 * When on, every received BGP UPDATE is validated against the
 * router's ROA table at import time; routes whose origin AS is
 * not authorized are rejected.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `r` must be a valid `lr_router_t`.
 */
int32_t lr_router_set_roa_validate(lr_router_t r, uint8_t enable);

/**
 * Add an OSPFv2 session with the library defaults: MTU 1500,
 * point-to-point network type, Normal (non-stub) area. Returns 0 with
 * the handle written to `out_handle`, `-1` on a null out pointer,
 * `-2` on an invalid router handle, `-3` when the router rejects the
 * configuration (mismatched router-id, area kind conflict, backbone
 * stub — the last-error string says which).
 *
 * # Safety
 * `out_handle` must be a writable `u64` when non-null.
 */
int32_t lr_router_add_ospf_session(lr_router_t r,
                                   uint32_t router_id,
                                   uint32_t area_id,
                                   uint64_t *out_handle);

/**
 * Add an OSPFv3 session (RFC 5340) with the library defaults. Router
 * IDs stay 32-bit and shared with OSPFv2 within one router; areas are
 * version-exclusive. Return/error codes as
 * [`lr_router_add_ospf_session`].
 *
 * # Safety
 * `out_handle` must be a writable `u64` when non-null.
 */
int32_t lr_router_add_ospfv3_session(lr_router_t r,
                                     uint32_t router_id,
                                     uint32_t area_id,
                                     uint64_t *out_handle);

/**
 * Add an OSPF session with the full knob set.
 *
 * * `version` — [`LR_OSPF_V2`] or [`LR_OSPF_V3`].
 * * `area_kind` — [`LR_AREA_NORMAL`], [`LR_AREA_STUB`],
 *   [`LR_AREA_STUB_NO_SUMMARY`], [`LR_AREA_NSSA`],
 *   [`LR_AREA_NSSA_NO_SUMMARY`]. The stub/NSSA kinds use
 *   `default_metric` for the border-router-injected default route.
 * * `mtu` — interface MTU announced in DBD packets (§10.6); 0 falls
 *   back to the 1500 default.
 * * `network_type` — [`LR_NET_PTP`] or [`LR_NET_BROADCAST`] (§9.4;
 *   broadcast gates adjacency on the elected DR/BDR, §10.4).
 * * `has_interface_ip` / `interface_ip` — our identity on the segment:
 *   the IPv4 interface address on v2 (§10.4, §12.4.1.2) or the Router
 *   ID on v3 (RFC 5340 §4.1.2). Ignored when `has_interface_ip` is 0.
 * * `has_neighbor_ip` / `neighbor_ip` — the neighbor's identity on
 *   the segment (v2 interface address / v3 Router ID), what the
 *   elected DR/BDR is compared against. Ignored when 0.
 *
 * Return codes: 0 ok, -1 null out pointer, -2 invalid handle, -3
 * malformed argument (unknown version/area kind/network type) or
 * rejected by the router, [`LR_ERR_PANIC`] on panic.
 *
 * # Safety
 * `out_handle` must be a writable `u64` when non-null.
 */
int32_t lr_router_add_ospf_session_ext(lr_router_t r,
                                       int32_t version,
                                       uint32_t router_id,
                                       uint32_t area_id,
                                       int32_t area_kind,
                                       uint32_t default_metric,
                                       uint16_t mtu,
                                       int32_t network_type,
                                       int32_t has_interface_ip,
                                       uint32_t interface_ip,
                                       int32_t has_neighbor_ip,
                                       uint32_t neighbor_ip,
                                       uint64_t *out_handle);

/**
 * Add one Babel interface session (RFC 8966). `local_addr` is the
 * 16-byte IPv6 address the interface announces in Hellos (§4.2.1) —
 * for IPv4 operation the embedder passes the v4-mapped form
 * (`::ffff:a.b.c.d`, `is_ipv6 = 0` selects the first four bytes).
 *
 * Return codes: 0 ok with the handle in `out_handle`, -1 null out
 * pointer, -2 invalid handle, [`LR_ERR_PANIC`] on panic.
 *
 * # Safety
 * `local_addr` must be a readable 16-byte array when non-null;
 * `out_handle` must be a writable `u64` when non-null.
 */
int32_t lr_router_add_babel_session(lr_router_t r,
                                    const uint8_t *local_addr,
                                    int32_t is_ipv6,
                                    uint64_t *out_handle);

/**
 * Encode an SRH from a list of SID bytes. Each SID is 16 bytes; the
 * caller passes a flat `data` of `len = n * 16` bytes. The encoded
 * SRH (RFC 8754 §2 wire form) is written to `*out`.
 *
 * Returns 0 on success, negative on error:
 * - `-1`: null pointer or `len` not a multiple of 16.
 * - `-4`: panic.
 * - `-5`: SRH encode error (set via `lr_last_error`).
 */
int32_t lr_srv6_encode_srh(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

/**
 * Decode an SRH from `data` (RFC 8754 §2 wire form). On success,
 * writes a freshly-allocated `lr_bytes_t` to `*out` carrying the
 * segment list bytes (16 octets per SID, concatenated in wire
 * order). The TLV bytes are appended after the segment list so the
 * caller can recover the full SRH body, but the typical caller
 * only needs the segment list.
 *
 * Returns 0 on success, negative on error:
 * - `-1`: null pointer.
 * - `-3`: input too short.
 * - `-4`: panic.
 * - `-5`: SRH decode error (set via `lr_last_error`).
 */
int32_t lr_srv6_decode_srh(const uint8_t *data, uintptr_t len, struct lr_bytes_t *out);

#endif  /* LR_FFI_H */
